#mysql:
#  build: ./mysql
#  volumes:
#    - data/mysql:/var/lib/mysql
#  environment:
#    - MYSQL_ROOT_PASSWORD=*******
#    - MYSQL_USER=ghost
#    - MYSQL_PASSWORD=******
#    - MYSQL_DATABASE=ghost

postgres:
  build: ./postgres
  volumes:
    - data/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=******
    - POSTGRES_USER=ghost
    - POSTGRES_DB=ghost
  
ghost:
  build: ./ghost
  volumes:
    - data/ghost/content:/usr/src/ghost/content
    - data/ghost/config:/var/lib/ghost
  links:
    - postgres:db
  environment:
    - DB_HOST=db
    - DB_CLIENT=pg
    - DB_USER=ghost
    - DB_PASSWORD=******
    - DB_DATABASE=ghost
    - DB_PORT=5432
    - NODE_ENV=production
    - URL=http://blog.site.com
    - MAIL_HOST=smtp.exmail.qq.com
    - MAIL_SERVICE=smtp.exmail.qq.com
    - MAIL_USER=email_user
    - MAIL_PASS=******


nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - ghost:ghost
